language: java
before_install:
- sudo apt-get -qq update
# ant-optional is needed for ant junit
- sudo apt-get install ant-optional
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # this is a virtual screen
  - sleep 3 # give xvfb some time to start
script: ant main
jdk:
  - oraclejdk8
notifications:
  slack: husacct:dzyOOT9XxkAKgVhRg5I72WSo`

